name = "drclash-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "drclash-db"
database_id = "86b82962-442b-4b7c-a03b-f8bbda99969a"

# Non-sensitive vars (secrets are set via wrangler secret put)
[vars]
APP_URL = "https://drclash.vercel.app"
RESEND_SENDER_EMAIL = "onboarding@resend.dev"
GOOGLE_CALLBACK_URL = "https://drclash-api.babarmeet86.workers.dev/api/auth/google/callback"
